[package]
name = "money_manager_backend"
version = "0.1.0"
edition = "2024"
authors = ["Marcos Gabriel Miller"]
license = "GPL-3.0"

[dependencies]
actix-web = "=4.12.0"
actix-http = "=3.11.2"
chrono = { version = "0.4.44", features = ["serde"] }
dotenvy = "0.15.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sea-orm = { version = "1.1.19", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "chrono", "with-uuid", "with-rust_decimal"] }
migrations = { path = "migrations" }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.22", features = ["v7", "serde"] }
validator = { version = "0.20.0", features = ["derive"] }
fancy-regex = "0.14.0"
argon2 = "0.5.3"
jsonwebtoken = { version = "10.3.0", default-features = false, features = ["rust_crypto"] }
thiserror = "2.0.18"
rust_decimal = { version = "1.40.0", features = ["serde"] }
env_logger = "0.11.9"
log = "0.4.29"
rand_core = { version = "0.6", features = ["getrandom"] }
time = "=0.3.36"
home = "=0.5.11"
utoipa = { version = "5", features = ["actix_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "8", features = ["actix-web"] }
seed_defaults = { path = "seed_defaults" }
casbin = "2.20.0"
lettre = { version = "0.11.20", default-features = false, features = ["builder", "smtp-transport", "tokio1-rustls", "ring", "webpki-roots", "pool"] }
