# Generated by Django 5.1.6 on 2025-03-04 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="users",
            field=models.ManyToManyField(
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
    ]
